version: "3"
services:
  db:
    image: mongo:7.0
    container_name: db
    ports:
      - '27018:27017'
    restart: always
    networks:
      - pollvoteapp_network
    volumes:
      - mongodb:/data/db

  pollvoteapp:
    image: quangsanh1501/pollvoteapp:latest
    container_name: pollvoteapp
    ports:
      - '${PORT}:${PORT}'  # Vẫn giữ nguyên mapping cũ
    depends_on:
      - db
    restart: always
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - pollvoteapp_network
      - proxy

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "81:81"   # Trang quản trị Nginx Proxy Manager
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy

networks:
  pollvoteapp_network:
    driver: bridge
  proxy:

volumes:
  mongodb:
    driver: local


    #
