services:
  db:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27018:27017'
    restart: always
    networks:
      - pollvoteapp_network
    volumes:
      - mongodb:/data/db

  myapp:
    image: quangsanh1501/pollvoteapp:latest
    container_name: pollvoteapp
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    restart: always
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - pollvoteapp_network

networks:
  pollvote_network:
    driver: bridge

volumes:
  mongodb:
    driver: local